version: "3.9"
services:
  web:
    image: python:3.12
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
